name: Build and Test
 
on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions: write-all

jobs:
  yarn-base-test:
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: yarn install
        env:
          NEXT_PUBLIC_AUTH0_DOMAIN: test
          NEXT_PUBLIC_AUTH0_CLIENT_ID: test
          NEXT_PUBLIC_CALLBACK_URL: http://localhost:3000
        run: yarn install && yarn lint --fix && yarn build
