name: Build and Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions: write-all

jobs:
  pnpm-base-test:
    strategy:
      matrix:
        node-version: [18.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: build
        env:
          NEXT_PUBLIC_AUTH0_DOMAIN: test
          NEXT_PUBLIC_AUTH0_CLIENT_ID: test
          NEXT_PUBLIC_CALLBACK_URL: http://localhost:3000
          CI: true
        run: pnpm install && pnpm lint-fix && pnpm build
